deployment:
  tasks:
    - export DEPLOYPATH=/home/kalende1/public_html/
    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH